import type {
  BetAcceptedPayload,
  BetRejectedPayload,
  BetStopAppliedPayload,
  BetStopLiftedPayload,
  MarketStatus,
  MarketStatusChangedPayload,
  OddsChangedPayload,
} from "@/contract/events";
import type { BetSelection } from "@/contract/rest";

// ---------------------------------------------------------------------------
// M13 — BetSlipStore
//
// Single-slip FSM (docs/.../04_state_machines.md §6):
//
//   Empty ──addSelection──▶ Editing ──validate──▶ Ready ──place──▶ Submitting
//                              ▲                    │                   │
//                              │                    │ priceChanged?     │
//                              └──acceptChange──────┤                   │
//                                                   ▼                   ▼
//                                              NeedsReview      Submitted | SubmitFailed
//                                                                          │ retry
//                                                                          ▼
//                                                                     Submitting
//
// Locked decisions (PR thread):
//   1. Dedicated `SubmitFailed` state with `retrySubmit()` → Submitting
//      (parallels M11's Failed/retryFromFailed).
//   2. `rejectPriceChange(position)` removes only that selection. If it was
//      the last, slip collapses to Empty; otherwise returns to Editing.
//   3. `place()` from NeedsReview is rejected — the user MUST acceptPriceChange
//      first (acceptance §2 of M13 doc).
//   4. Idempotency key is generated by the caller on the first `place()` and
//      preserved across retries; `reset()` clears the key.
//   5. Availability: empty `market_groups` on bet_stop.applied = full-match
//      block (per contract); non-empty = scoped block keyed by market_group.
//      Market suspension blocks placement at the market_id level.
// ---------------------------------------------------------------------------

export type BetSlipState =
  | "Empty"
  | "Editing"
  | "Ready"
  | "NeedsReview"
  | "Submitting"
  | "Submitted"
  | "SubmitFailed";

export type BetType = "single" | "multiple" | "system";

export interface SlipSelection extends BetSelection {
  /**
   * Optional market_group hint for bet_stop scoping. When undefined,
   * only full-match bet_stop will block this selection.
   */
  market_group?: string;
}

export interface SlipPriceChange {
  position: number;
  from: number;
  to: number;
}

export interface SlipValidationReason {
  code: string;
  selection_position?: number;
  message: string;
}

export interface SlipRejection {
  code: string;
  message: string;
  bet_id?: string;
}

export interface PlacementGate {
  ok: boolean;
  reasons: SlipBlockReason[];
}

export type SlipBlockReason =
  | { kind: "wrong_state"; state: BetSlipState }
  | { kind: "no_selections" }
  | { kind: "missing_stake" }
  | { kind: "missing_currency" }
  | { kind: "market_suspended"; market_id: string; position: number }
  | { kind: "bet_stop"; match_id: string; position: number };

export interface BetSlipTelemetry {
  illegalTransition(record: {
    from: BetSlipState;
    op: string;
  }): void;
}

export interface BetSlipStoreOptions {
  telemetry?: BetSlipTelemetry;
}

interface InternalState {
  state: BetSlipState;
  selections: SlipSelection[];
  stake?: number;
  currency?: string;
  bet_type: BetType;
  idempotency_key?: string;
  bet_id?: string;
  last_rejection?: SlipRejection;
  price_changes: SlipPriceChange[];
  validation_reasons: SlipValidationReason[];
}

type BetStopScope = "full" | Set<string>;

export class BetSlipStore {
  private slip: InternalState = makeEmpty();
  private readonly marketStatus = new Map<string, MarketStatus>();
  private readonly betStop = new Map<string, BetStopScope>();
  private readonly listeners = new Set<() => void>();
  private readonly telemetry?: BetSlipTelemetry;

  constructor(opts: BetSlipStoreOptions = {}) {
    this.telemetry = opts.telemetry;
  }

  // -------------------------------------------------------------------------
  // Mutation — Empty/Editing surface
  // -------------------------------------------------------------------------

  addSelection(sel: SlipSelection): boolean {
    if (
      this.slip.state !== "Empty" &&
      this.slip.state !== "Editing" &&
      this.slip.state !== "Ready" &&
      this.slip.state !== "NeedsReview"
    ) {
      this.reportIllegal("addSelection");
      return false;
    }
    // Reject duplicate position.
    if (this.slip.selections.some((s) => s.position === sel.position)) {
      return false;
    }
    this.slip.selections = [...this.slip.selections, { ...sel }];
    // Any mutation invalidates a Ready/NeedsReview validation.
    this.slip.state = "Editing";
    this.slip.validation_reasons = [];
    this.slip.price_changes = [];
    this.notify();
    return true;
  }

  removeSelection(position: number): boolean {
    const before = this.slip.selections.length;
    this.slip.selections = this.slip.selections.filter(
      (s) => s.position !== position,
    );
    if (this.slip.selections.length === before) return false;
    this.slip.validation_reasons = [];
    this.slip.price_changes = this.slip.price_changes.filter(
      (p) => p.position !== position,
    );
    if (this.slip.selections.length === 0) {
      this.slip.state = "Empty";
      this.slip.stake = undefined;
    } else {
      this.slip.state = "Editing";
    }
    this.notify();
    return true;
  }

  setStake(stake: number, currency: string): boolean {
    if (
      this.slip.state !== "Editing" &&
      this.slip.state !== "Ready" &&
      this.slip.state !== "NeedsReview"
    ) {
      this.reportIllegal("setStake");
      return false;
    }
    if (!(stake > 0)) return false;
    this.slip.stake = stake;
    this.slip.currency = currency;
    if (this.slip.state === "Ready") this.slip.state = "Editing";
    this.notify();
    return true;
  }

  setBetType(betType: BetType): boolean {
    if (
      this.slip.state !== "Empty" &&
      this.slip.state !== "Editing" &&
      this.slip.state !== "Ready" &&
      this.slip.state !== "NeedsReview"
    ) {
      this.reportIllegal("setBetType");
      return false;
    }
    if (this.slip.bet_type === betType) return false;
    this.slip.bet_type = betType;
    if (this.slip.state === "Ready") this.slip.state = "Editing";
    this.notify();
    return true;
  }

  // -------------------------------------------------------------------------
  // Validation transitions
  // -------------------------------------------------------------------------

  markValidated(): boolean {
    if (this.slip.state !== "Editing") {
      this.reportIllegal("markValidated");
      return false;
    }
    if (this.slip.selections.length === 0) return false;
    if (this.slip.stake === undefined || this.slip.currency === undefined) {
      return false;
    }
    this.slip.state = "Ready";
    this.slip.validation_reasons = [];
    this.notify();
    return true;
  }

  markInvalid(reasons: SlipValidationReason[]): boolean {
    if (this.slip.state !== "Editing") {
      this.reportIllegal("markInvalid");
      return false;
    }
    this.slip.validation_reasons = reasons.map((r) => ({ ...r }));
    this.notify();
    return true;
  }

  // -------------------------------------------------------------------------
  // Submission transitions
  // -------------------------------------------------------------------------

  place(idempotencyKey: string): boolean {
    if (this.slip.state !== "Ready") {
      // place() from NeedsReview / Submitting / Submitted / etc. is illegal.
      this.reportIllegal("place");
      return false;
    }
    const gate = this.canPlace();
    if (!gate.ok) return false;
    this.slip.state = "Submitting";
    this.slip.idempotency_key = idempotencyKey;
    this.slip.last_rejection = undefined;
    this.notify();
    return true;
  }

  retrySubmit(): boolean {
    if (this.slip.state !== "SubmitFailed") {
      this.reportIllegal("retrySubmit");
      return false;
    }
    if (!this.slip.idempotency_key) return false;
    this.slip.state = "Submitting";
    this.slip.last_rejection = undefined;
    this.notify();
    return true;
  }

  reset(): void {
    this.slip = makeEmpty();
    this.notify();
  }

  // -------------------------------------------------------------------------
  // Wire reducers — bet.accepted / bet.rejected
  // -------------------------------------------------------------------------

  applyBetAccepted(payload: BetAcceptedPayload): boolean {
    if (this.slip.state !== "Submitting") return false;
    this.slip.state = "Submitted";
    this.slip.bet_id = payload.bet_id;
    this.slip.last_rejection = undefined;
    this.notify();
    return true;
  }

  applyBetRejected(payload: BetRejectedPayload): boolean {
    if (this.slip.state !== "Submitting") return false;
    this.slip.state = "SubmitFailed";
    this.slip.last_rejection = {
      code: payload.code,
      message: payload.message,
      bet_id: payload.bet_id,
    };
    this.notify();
    return true;
  }

  // -------------------------------------------------------------------------
  // Wire reducers — odds.changed (NeedsReview)
  // -------------------------------------------------------------------------

  applyOddsChanged(payload: OddsChangedPayload): boolean {
    if (
      this.slip.state !== "Ready" &&
      this.slip.state !== "NeedsReview"
    ) {
      return false;
    }
    let mutated = false;
    const next = [...this.slip.price_changes];
    for (const o of payload.outcomes) {
      const idx = this.slip.selections.findIndex(
        (s) =>
          s.market_id === payload.market_id &&
          s.outcome_id === o.outcome_id &&
          s.match_id === payload.match_id,
      );
      if (idx === -1) continue;
      const sel = this.slip.selections[idx]!;
      if (sel.locked_odds === o.odds) continue;
      const existing = next.findIndex((p) => p.position === sel.position);
      const change: SlipPriceChange = {
        position: sel.position,
        from: sel.locked_odds,
        to: o.odds,
      };
      if (existing === -1) next.push(change);
      else next[existing] = change;
      mutated = true;
    }
    if (!mutated) return false;
    this.slip.price_changes = next;
    this.slip.state = "NeedsReview";
    this.notify();
    return true;
  }

  acceptPriceChange(position: number): boolean {
    if (this.slip.state !== "NeedsReview") {
      this.reportIllegal("acceptPriceChange");
      return false;
    }
    const idx = this.slip.price_changes.findIndex(
      (p) => p.position === position,
    );
    if (idx === -1) return false;
    const change = this.slip.price_changes[idx]!;
    this.slip.selections = this.slip.selections.map((s) =>
      s.position === position ? { ...s, locked_odds: change.to } : s,
    );
    this.slip.price_changes = this.slip.price_changes.filter(
      (p) => p.position !== position,
    );
    if (this.slip.price_changes.length === 0) this.slip.state = "Ready";
    this.notify();
    return true;
  }

  rejectPriceChange(position: number): boolean {
    if (this.slip.state !== "NeedsReview") {
      this.reportIllegal("rejectPriceChange");
      return false;
    }
    const before = this.slip.selections.length;
    this.slip.selections = this.slip.selections.filter(
      (s) => s.position !== position,
    );
    if (this.slip.selections.length === before) return false;
    this.slip.price_changes = this.slip.price_changes.filter(
      (p) => p.position !== position,
    );
    if (this.slip.selections.length === 0) {
      this.slip.state = "Empty";
      this.slip.stake = undefined;
    } else if (this.slip.price_changes.length === 0) {
      this.slip.state = "Editing";
    }
    this.notify();
    return true;
  }

  // -------------------------------------------------------------------------
  // Wire reducers — availability (market status / bet_stop)
  // -------------------------------------------------------------------------

  applyMarketStatusChanged(payload: MarketStatusChangedPayload): boolean {
    const prev = this.marketStatus.get(payload.market_id);
    if (prev === payload.status) return false;
    this.marketStatus.set(payload.market_id, payload.status);
    if (this.slipReferencesMarket(payload.market_id)) {
      this.notify();
    }
    return true;
  }

  applyBetStopApplied(payload: BetStopAppliedPayload): boolean {
    const scope: BetStopScope =
      payload.market_groups.length === 0
        ? "full"
        : new Set(payload.market_groups);
    this.betStop.set(payload.match_id, scope);
    if (this.slipReferencesMatch(payload.match_id)) this.notify();
    return true;
  }

  applyBetStopLifted(payload: BetStopLiftedPayload): boolean {
    if (!this.betStop.has(payload.match_id)) return false;
    if (payload.market_groups.length === 0) {
      this.betStop.delete(payload.match_id);
    } else {
      const scope = this.betStop.get(payload.match_id);
      if (scope === "full") {
        // Partial lift over a full-match stop is treated as full lift.
        this.betStop.delete(payload.match_id);
      } else if (scope) {
        for (const g of payload.market_groups) scope.delete(g);
        if (scope.size === 0) this.betStop.delete(payload.match_id);
      }
    }
    if (this.slipReferencesMatch(payload.match_id)) this.notify();
    return true;
  }

  // -------------------------------------------------------------------------
  // Selectors
  // -------------------------------------------------------------------------

  getState(): BetSlipState {
    return this.slip.state;
  }

  getSelections(): SlipSelection[] {
    return this.slip.selections.map((s) => ({ ...s }));
  }

  getStake(): number | undefined {
    return this.slip.stake;
  }

  getCurrency(): string | undefined {
    return this.slip.currency;
  }

  getBetType(): BetType {
    return this.slip.bet_type;
  }

  getIdempotencyKey(): string | undefined {
    return this.slip.idempotency_key;
  }

  getBetId(): string | undefined {
    return this.slip.bet_id;
  }

  getPriceChanges(): SlipPriceChange[] {
    return this.slip.price_changes.map((p) => ({ ...p }));
  }

  getLastRejection(): SlipRejection | undefined {
    return this.slip.last_rejection
      ? { ...this.slip.last_rejection }
      : undefined;
  }

  getValidationReasons(): SlipValidationReason[] {
    return this.slip.validation_reasons.map((r) => ({ ...r }));
  }

  canPlace(): PlacementGate {
    const reasons: SlipBlockReason[] = [];
    if (this.slip.state !== "Ready") {
      reasons.push({ kind: "wrong_state", state: this.slip.state });
    }
    if (this.slip.selections.length === 0) {
      reasons.push({ kind: "no_selections" });
    }
    if (this.slip.stake === undefined) reasons.push({ kind: "missing_stake" });
    if (this.slip.currency === undefined) {
      reasons.push({ kind: "missing_currency" });
    }
    for (const sel of this.slip.selections) {
      const status = this.marketStatus.get(sel.market_id);
      if (status && status !== "active") {
        reasons.push({
          kind: "market_suspended",
          market_id: sel.market_id,
          position: sel.position,
        });
      }
      const scope = this.betStop.get(sel.match_id);
      if (scope !== undefined) {
        if (
          scope === "full" ||
          (sel.market_group && scope.has(sel.market_group))
        ) {
          reasons.push({
            kind: "bet_stop",
            match_id: sel.match_id,
            position: sel.position,
          });
        }
      }
    }
    return { ok: reasons.length === 0, reasons };
  }

  subscribe(handler: () => void): () => void {
    this.listeners.add(handler);
    return () => {
      this.listeners.delete(handler);
    };
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------

  private slipReferencesMarket(marketId: string): boolean {
    return this.slip.selections.some((s) => s.market_id === marketId);
  }

  private slipReferencesMatch(matchId: string): boolean {
    return this.slip.selections.some((s) => s.match_id === matchId);
  }

  private reportIllegal(op: string): void {
    this.telemetry?.illegalTransition({ from: this.slip.state, op });
  }

  private notify(): void {
    for (const l of this.listeners) l();
  }
}

function makeEmpty(): InternalState {
  return {
    state: "Empty",
    selections: [],
    stake: undefined,
    currency: undefined,
    bet_type: "single",
    idempotency_key: undefined,
    bet_id: undefined,
    last_rejection: undefined,
    price_changes: [],
    validation_reasons: [],
  };
}
