// frontend/src/betSlip/store.test.ts
//
// M13 — BetSlip FSM + price-change + availability gating.
// Locked decisions per PR thread:
//   1. Dedicated SubmitFailed state with retrySubmit() → Submitting
//   2. rejectPriceChange(position) removes only that selection
//   3. place() from NeedsReview is rejected (must acceptPriceChange first)
//   4. Idempotency key generated by caller on place(); preserved on retry; cleared on reset()

import { describe, expect, it, vi } from "vitest";

import type {
  BetAcceptedPayload,
  BetRejectedPayload,
  BetStopAppliedPayload,
  BetStopLiftedPayload,
  MarketStatusChangedPayload,
  OddsChangedPayload,
} from "@/contract/events";

import { BetSlipStore, type SlipSelection } from "./store";

function sel(
  position: number,
  overrides: Partial<SlipSelection> = {},
): SlipSelection {
  return {
    position,
    match_id: "m1",
    market_id: "mk1",
    outcome_id: "home",
    locked_odds: 2.0,
    ...overrides,
  };
}

function oddsChanged(
  args: Partial<OddsChangedPayload> & {
    match_id: string;
    market_id: string;
    outcomes: OddsChangedPayload["outcomes"];
  },
): OddsChangedPayload {
  return {
    version: 1,
    ...args,
  };
}

function readyStore(): BetSlipStore {
  const s = new BetSlipStore();
  s.addSelection(sel(1));
  s.setStake(10, "USD");
  s.markValidated();
  return s;
}

// =================== FSM transitions ===================

describe("M13 betSlip FSM: Empty → Editing on addSelection", () => {
  it("when the first selection is added then state becomes Editing and the selection is appended", () => {
    const s = new BetSlipStore();
    expect(s.getState()).toBe("Empty");
    expect(s.addSelection(sel(1))).toBe(true);
    expect(s.getState()).toBe("Editing");
    expect(s.getSelections()).toHaveLength(1);
    expect(s.getSelections()[0]?.outcome_id).toBe("home");
  });
});

describe("M13 betSlip FSM: Editing → Empty on remove-last", () => {
  it("when the last remaining selection is removed then state returns to Empty", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1));
    expect(s.removeSelection(1)).toBe(true);
    expect(s.getState()).toBe("Empty");
    expect(s.getSelections()).toHaveLength(0);
  });
});

describe("M13 betSlip FSM: Editing → Ready on validate ok", () => {
  it("when validate succeeds then state becomes Ready", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1));
    s.setStake(20, "USD");
    expect(s.markValidated()).toBe(true);
    expect(s.getState()).toBe("Ready");
  });
});

describe("M13 betSlip FSM: Editing stays Editing on validate fail", () => {
  it("when validate fails then state remains Editing and reasons are exposed", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1));
    s.setStake(20, "USD");
    expect(
      s.markInvalid([{ code: "STAKE_TOO_LOW", message: "minimum 50" }]),
    ).toBe(true);
    expect(s.getState()).toBe("Editing");
    expect(s.getValidationReasons()).toEqual([
      { code: "STAKE_TOO_LOW", message: "minimum 50" },
    ]);
  });
});

describe("M13 betSlip FSM: Ready → Submitting on place", () => {
  it("when place is invoked then state becomes Submitting and idempotency key is recorded", () => {
    const s = readyStore();
    expect(s.place("idem-1")).toBe(true);
    expect(s.getState()).toBe("Submitting");
    expect(s.getIdempotencyKey()).toBe("idem-1");
  });
});

describe("M13 betSlip FSM: Submitting → Submitted on bet.accepted", () => {
  it("when bet.accepted arrives then state becomes Submitted with bet_id", () => {
    const s = readyStore();
    s.place("idem-1");
    const accepted: BetAcceptedPayload = {
      bet_id: "bet-42",
      user_id: "u1",
      accepted_odds: 2.0,
      accepted_at: "2026-05-16T07:00:00Z",
    };
    expect(s.applyBetAccepted(accepted)).toBe(true);
    expect(s.getState()).toBe("Submitted");
    expect(s.getBetId()).toBe("bet-42");
  });
});

describe("M13 betSlip FSM: Submitting → SubmitFailed on bet.rejected", () => {
  it("when bet.rejected arrives then state becomes SubmitFailed with reason", () => {
    const s = readyStore();
    s.place("idem-1");
    const rejected: BetRejectedPayload = {
      bet_id: "bet-42",
      user_id: "u1",
      code: "PRICE_CHANGED",
      message: "Odds moved",
    };
    expect(s.applyBetRejected(rejected)).toBe(true);
    expect(s.getState()).toBe("SubmitFailed");
    expect(s.getLastRejection()).toEqual({
      code: "PRICE_CHANGED",
      message: "Odds moved",
      bet_id: "bet-42",
    });
  });
});

describe("M13 betSlip retry: SubmitFailed → Submitting reuses key", () => {
  it("when retrySubmit is invoked then the same idempotency key is reused", () => {
    const s = readyStore();
    s.place("idem-1");
    s.applyBetRejected({
      bet_id: "bet-42",
      user_id: "u1",
      code: "GATEWAY",
      message: "try again",
    });
    expect(s.retrySubmit()).toBe(true);
    expect(s.getState()).toBe("Submitting");
    expect(s.getIdempotencyKey()).toBe("idem-1");
    expect(s.getLastRejection()).toBeUndefined();
  });
});

// =================== Price-change watcher ===================

describe("M13 betSlip price-change: Ready → NeedsReview on odds.changed", () => {
  it("when odds for a slip selection change then NeedsReview is entered with delta", () => {
    const s = readyStore();
    const ok = s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk1",
        outcomes: [{ outcome_id: "home", odds: 1.9, active: true }],
      }),
    );
    expect(ok).toBe(true);
    expect(s.getState()).toBe("NeedsReview");
    expect(s.getPriceChanges()).toEqual([{ position: 1, from: 2.0, to: 1.9 }]);
  });
});

describe("M13 betSlip price-change: acceptPriceChange returns to Ready", () => {
  it("when the user accepts the new odds then state returns to Ready with updated locked odds", () => {
    const s = readyStore();
    s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk1",
        outcomes: [{ outcome_id: "home", odds: 1.9, active: true }],
      }),
    );
    expect(s.acceptPriceChange(1)).toBe(true);
    expect(s.getState()).toBe("Ready");
    expect(s.getSelections()[0]?.locked_odds).toBe(1.9);
    expect(s.getPriceChanges()).toHaveLength(0);
  });
});

describe("M13 betSlip price-change: rejectPriceChange removes selection", () => {
  it("when the user rejects the price change then the only selection is removed and slip collapses to Empty", () => {
    const s = readyStore();
    s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk1",
        outcomes: [{ outcome_id: "home", odds: 1.9, active: true }],
      }),
    );
    expect(s.rejectPriceChange(1)).toBe(true);
    expect(s.getState()).toBe("Empty");
    expect(s.getSelections()).toHaveLength(0);
  });

  it("when one of multiple selections is rejected then it is removed and slip returns to Editing", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1));
    s.addSelection(sel(2, { market_id: "mk2", outcome_id: "away" }));
    s.setStake(50, "USD");
    s.markValidated();
    s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk2",
        outcomes: [{ outcome_id: "away", odds: 3.5, active: true }],
      }),
    );
    expect(s.rejectPriceChange(2)).toBe(true);
    expect(s.getState()).toBe("Editing");
    expect(s.getSelections()).toHaveLength(1);
    expect(s.getSelections()[0]?.position).toBe(1);
  });
});

describe("M13 betSlip price-change: irrelevant odds ignored", () => {
  it("when odds change on a non-slip selection then the slip is unchanged", () => {
    const s = readyStore();
    const ok = s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk99", // not in slip
        outcomes: [{ outcome_id: "home", odds: 1.5, active: true }],
      }),
    );
    expect(ok).toBe(false);
    expect(s.getState()).toBe("Ready");
    expect(s.getPriceChanges()).toHaveLength(0);
  });
});

describe("M13 betSlip place from NeedsReview: rejected", () => {
  it("when place is called while NeedsReview then the call is rejected (locked decision #3)", () => {
    const telemetry = { illegalTransition: vi.fn() };
    const s = new BetSlipStore({ telemetry });
    s.addSelection(sel(1));
    s.setStake(10, "USD");
    s.markValidated();
    s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "mk1",
        outcomes: [{ outcome_id: "home", odds: 1.9, active: true }],
      }),
    );
    expect(s.getState()).toBe("NeedsReview");
    expect(s.place("idem-x")).toBe(false);
    expect(s.getState()).toBe("NeedsReview");
    expect(s.getIdempotencyKey()).toBeUndefined();
    expect(telemetry.illegalTransition).toHaveBeenCalledWith({
      from: "NeedsReview",
      op: "place",
    });
  });
});

// =================== Availability gating ===================

describe("M13 betSlip availability: market suspension blocks placement", () => {
  it("when a slip's market becomes suspended then canPlace is false with market_suspended reason", () => {
    const s = readyStore();
    const payload: MarketStatusChangedPayload = {
      match_id: "m1",
      market_id: "mk1",
      status: "suspended",
      version: 1,
    };
    expect(s.applyMarketStatusChanged(payload)).toBe(true);
    const gate = s.canPlace();
    expect(gate.ok).toBe(false);
    expect(gate.reasons).toContainEqual({
      kind: "market_suspended",
      market_id: "mk1",
      position: 1,
    });
  });
});

describe("M13 betSlip availability: bet_stop blocks placement", () => {
  it("when full-match bet_stop targets the slip's match then canPlace is false with bet_stop reason", () => {
    const s = readyStore();
    const payload: BetStopAppliedPayload = {
      match_id: "m1",
      market_groups: [],
    };
    expect(s.applyBetStopApplied(payload)).toBe(true);
    const gate = s.canPlace();
    expect(gate.ok).toBe(false);
    expect(gate.reasons).toContainEqual({
      kind: "bet_stop",
      match_id: "m1",
      position: 1,
    });
  });

  it("when scoped bet_stop targets a market_group the selection belongs to then canPlace is false", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1, { market_group: "main" }));
    s.setStake(10, "USD");
    s.markValidated();
    s.applyBetStopApplied({ match_id: "m1", market_groups: ["main"] });
    expect(s.canPlace().ok).toBe(false);
  });

  it("when scoped bet_stop targets a different market_group then canPlace is true", () => {
    const s = new BetSlipStore();
    s.addSelection(sel(1, { market_group: "main" }));
    s.setStake(10, "USD");
    s.markValidated();
    s.applyBetStopApplied({ match_id: "m1", market_groups: ["specials"] });
    expect(s.canPlace().ok).toBe(true);
  });
});

describe("M13 betSlip availability: bet_stop lifted re-enables", () => {
  it("when bet_stop is lifted then canPlace returns true again", () => {
    const s = readyStore();
    s.applyBetStopApplied({ match_id: "m1", market_groups: [] });
    expect(s.canPlace().ok).toBe(false);
    const lifted: BetStopLiftedPayload = { match_id: "m1", market_groups: [] };
    expect(s.applyBetStopLifted(lifted)).toBe(true);
    expect(s.canPlace().ok).toBe(true);
  });
});

// =================== Idempotency / reset ===================

describe("M13 betSlip idempotency: key is stable across retries", () => {
  it("when retrySubmit fires repeatedly then the idempotency key remains stable", () => {
    const s = readyStore();
    s.place("idem-1");
    s.applyBetRejected({
      bet_id: "bet-x",
      user_id: "u1",
      code: "X",
      message: "x",
    });
    s.retrySubmit();
    expect(s.getIdempotencyKey()).toBe("idem-1");
    s.applyBetRejected({
      bet_id: "bet-x",
      user_id: "u1",
      code: "X",
      message: "x",
    });
    s.retrySubmit();
    expect(s.getIdempotencyKey()).toBe("idem-1");
  });
});

describe("M13 betSlip reset: Submitted → Empty clears key and bet_id", () => {
  it("when reset is invoked then state returns to Empty and idempotency key/bet_id are cleared", () => {
    const s = readyStore();
    s.place("idem-1");
    s.applyBetAccepted({
      bet_id: "bet-42",
      user_id: "u1",
      accepted_odds: 2.0,
      accepted_at: "2026-05-16T07:00:00Z",
    });
    expect(s.getState()).toBe("Submitted");
    s.reset();
    expect(s.getState()).toBe("Empty");
    expect(s.getIdempotencyKey()).toBeUndefined();
    expect(s.getBetId()).toBeUndefined();
    expect(s.getSelections()).toHaveLength(0);
  });
});

describe("M13 betSlip idempotency: double-place while Submitting is no-op", () => {
  it("when place is invoked twice rapidly then the second call is rejected and key is preserved", () => {
    const telemetry = { illegalTransition: vi.fn() };
    const s = new BetSlipStore({ telemetry });
    s.addSelection(sel(1));
    s.setStake(10, "USD");
    s.markValidated();
    expect(s.place("idem-1")).toBe(true);
    expect(s.place("idem-2")).toBe(false);
    expect(s.getIdempotencyKey()).toBe("idem-1");
    expect(telemetry.illegalTransition).toHaveBeenCalledWith({
      from: "Submitting",
      op: "place",
    });
  });
});

// =================== Listeners ===================

describe("M13 betSlip listeners: fire on real mutations only", () => {
  it("when state actually changes the listener fires; otherwise it does not", () => {
    const s = new BetSlipStore();
    const listener = vi.fn();
    s.subscribe(listener);

    s.addSelection(sel(1));
    expect(listener).toHaveBeenCalledTimes(1);

    // Duplicate position is rejected, no notify.
    s.addSelection(sel(1));
    expect(listener).toHaveBeenCalledTimes(1);

    s.setStake(10, "USD");
    expect(listener).toHaveBeenCalledTimes(2);

    s.markValidated();
    expect(listener).toHaveBeenCalledTimes(3);

    // Irrelevant odds change doesn't notify.
    s.applyOddsChanged(
      oddsChanged({
        match_id: "m1",
        market_id: "other",
        outcomes: [{ outcome_id: "home", odds: 1.5, active: true }],
      }),
    );
    expect(listener).toHaveBeenCalledTimes(3);
  });
});
